language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.9"

os:
  - linux

install:
  - pip install -r requirements.txt

script:
  - pipenv run pytest

deploy:
  provider: pypi
  user: opaka
  password:
    secure: pypi-AgEIcHlwaS5vcmcCJDI0N2MyYmFkLTk3NGMtNGYzNS1hNTFlLWNhMjkyYmZhNmMwNgACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgSOMZhC82mn0DRBb5iNZvKIlnwe4CbKK4p5Ff992rMxw
  on:
    tags: true
